name: 'CI setup'
description: 'Configures environment for testing.'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm get cache)"
      shell: bash

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          ${{ steps.npm-cache-dir-path.outputs.dir }}
          node_modules
        key: ${{ runner.os }}-core-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-npm-
    - name: Install Dependencies
      run: | 
        npm ci
      shell: bash