name: 'CI setup'
description: 'Configures environment for testing.'

inputs:
  path:
    default: .
    description: Module path
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm config get cache)"
      shell: bash

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          ${{ inputs.path }}/${{ steps.npm-cache-dir-path.outputs.dir }}
          ${{ inputs.path }}/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/${{ inputs.path }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install Dependencies
      working-directory: ${{ inputs.path }}
      run: | 
        npm ci
      shell: bash