name: wrapper_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  environment_config: ^3.1.0
  permission_handler: ^9.2.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  dio: ^4.0.6
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.3
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  flutter_form_builder: ^7.3.1
  form_builder_validators: ^8.1.1
  json_serializable: ^6.2.0
  pub_semver: ^2.1.1
  package_info_plus: ^1.4.2

dev_dependencies:
  injectable_generator: ^1.5.4
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true