name: Core testing

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - core/**

jobs:
  core_unit_testing:
    name: Core Unit testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        index: [ 0 ]

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup
        with:
          path: core
          run: |
            npx graphql-codegen --config codegen.json

      - name: Running tests
        working-directory: core
        run: |
          env $(grep -v '^#' ../deploy/.envs/test | xargs -0) \
          npx jest \
            --runInBand \
            --passWithNoTests \
            --testTimeout=60000 \
            --testRegex .unit.test.ts$
        env:
          CI_NODE_TOTAL: 1
          CI_NODE_INDEX: ${{ matrix.index }}

  core_api_testing:
    name: Core API testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        index: [ 0 ]

    services:
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
      db:
        image: postgres:alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: test123123
          POSTGRES_USER: dbadmin
          POSTGRES_DB: timetrack
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup
        with:
          path: core
          run: |
            npx graphql-codegen --config codegen.json

      - name: Running tests
        working-directory: core
        run: |
          env $(grep -v '^#' ../deploy/.envs/test | xargs -0) \
          npx jest \
            --runInBand \
            --passWithNoTests \
            --testTimeout=60000 \
            --testRegex .api.test.ts$
        env:
          CI_NODE_TOTAL: 1
          CI_NODE_INDEX: ${{ matrix.index }}